name: Load Test

on:
  push:
    branches: [staging]  # only runs on staging branch

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask app
        run: |
          nohup python app.py &
          sleep 5  # wait for the server to start

      - name: Run Locust load test
        run: make loadtest
